# Generated by Django 2.2.5 on 2020-01-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0003_auto_20200112_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='project',
        ),
        migrations.AddField(
            model_name='profile',
            name='p_d',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='p_t',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
