# Generated by Django 2.2.5 on 2020-01-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0004_auto_20200112_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='achievements',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='degree',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='grade',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='p_d',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='p_t',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='previous_work',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='summary',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='university',
            field=models.CharField(default='', max_length=200),
        ),
    ]
