# Generated by Django 2.2.5 on 2020-02-12 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0005_auto_20200125_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='declaration',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='p_d',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='p_t',
        ),
    ]
