# Generated by Django 2.2.5 on 2020-03-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0009_auto_20200306_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='grade',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
