# Generated by Django 2.2.5 on 2020-03-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0010_auto_20200306_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='achievements',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='profile',
            name='declaration',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='profile',
            name='p_d',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='profile',
            name='p_t',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='grade',
            field=models.FloatField(),
        ),
    ]
