# Generated by Django 2.2.5 on 2020-03-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0012_auto_20200316_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='declaration',
        ),
        migrations.AlterField(
            model_name='profile',
            name='grade',
            field=models.CharField(max_length=10),
        ),
    ]
