# Generated by Django 2.2.5 on 2020-03-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0013_auto_20200316_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='p_d',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='p_t',
            field=models.TextField(max_length=1000),
        ),
    ]
